apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agro-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    notifications.argoproj.io/subscribe.sync-operation-change.teams: argocd-alerts
spec:
  project: default
  source:
    repoURL: ""
    targetRevision: HEAD
    path: bootstrap/agro-ingress

  destination:
    namespace: argocd
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
